[package]
name = "chemic"
version = "0.1.1"
edition = "2021"
description = "Microphone testing tool"
license = "MIT"
readme = "README.md"
authors = ["Jacobtread <jacobtread@gmail.com>"]
keywords = ["Microphone", "Testing"]
repository = "https://github.com/jacobtread/chemic"

[dependencies]
cpal = "0.15.0"
dialoguer = "0.10.3"
